services:
  meilisearch:
    image: getmeili/meilisearch:v1.37
    container_name: k8s-notes-meilisearch
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: dev-master-key-change-later
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
